version: '3'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: base-app_development
      POSTGRES_PASSWORD: rails
    ports:
      - '5432:5432'
    volumes:
      - base-app-postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:3.0.5
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - base-app-redis:/var/lib/redis/data

  web:
    build: .
    links:
      - "postgres:container_db.local"
      # - redis
    volumes:
      - .:/base-app
    ports:
      - '8000:8000'
    env_file:
      - ./config/environments/.app.env
      - ./config/environments/.app_dev.env

volumes:
  base-app-postgres: